name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  PG_VER: 16    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PostgreSQL
      uses: tj-actions/install-postgresql@v3
      with:
        postgresql-version: ${{ env.PG_VER }}
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y postgresql-server-dev-${{ env.PG_VER }}
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: Start PostgreSQL service
      run: sudo systemctl start postgresql.service
    - name: make test
      run: make installcheck
    - name: Add extension to PostgreSQL
      run: sudo -u postgres psql postgres -c "CREATE EXTENSION check_chapmd5_password"
    - name: Test extension check_chapmd5_password
      run: sudo -u postgres psql postgres -c "EXPLAIN (ANALYZE, TIMING, FORMAT YAML) SELECT check_chapmd5_password('00777f2a3f6a2e661947b520c6777e0b25', '45c915d82d67257209048420a31292d3', 'password')"

#      auto_tests:
#        name: Auto Tests    
#        runs-on: ubuntu-latest
#        needs: build
#        steps:
